### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by rauchi12** [htl-perg-2019-20-5ahif/travel-planner-api-rauchi12#1]
@not-matthias and I implemented all the required features.

**Comment by rstropek** [comment]
Nearly. Please use `IHttpClientFactory` in ASP.NET Core apps to get an instance of `HttpClient` (see [this slide](http://htl-mobile-computing-5.azurewebsites.net/#/6/1) and [this video](https://youtu.be/hj0joKgs01c?t=2512)). Fix that and the two extra points will be yours.

**Comment by rauchi12** [comment]
Added the IHttpClientFactory. Hope it's fine now.
